services:

stages:
- build

job1:
  stage: build
  script:
  - pwd
  - make clean
  - make -j3 release-static-64-devnet
  - make -j3 debug-test
  - make -j3
  - make -j3 debug-devnet
  - echo "job1 succesfully completed!"
  tags:
  - citicash
