services:

stages:
  - clean
  - build


job1:
  stage: clean
  script:
  - pwd
  - make clean-force
  - echo "Clean force succesfully completed!"
  tags:
  - citicash

build1:
  stage: build
  script:
    - pwd
    - make -j1 release-static-64-devnet
    - echo "Build no.:1 succesfully completed!"
  tags:
  - citicash
  
build2:
  stage: build
  script:
    - pwd
    - make -j1 debug-test
    - echo "Build no.:2 succesfully completed!"
  tags:
  - citicash
  
build3:
  stage: build
  script:
    - pwd
    - make -j2
    - echo "Build no.:3 succesfully completed!"
  tags:
  - citicash
  
build4:
  stage: build
  script:
    - pwd
    - make -j2 debug-devnet
    - echo "Build no.:4 succesfully completed!"
  tags:
  - citicash
