services:

stages:
- build

job1:
  stage: build
  script:
  - pwd
  - rm -rf "%CACHE_PATH%"
  - make -j3 release-static-64-devnet
  - make -j3 debug-test
  - echo "job1 succesfully completed!"
  tags:
  - citicash
